const eventsStore = [
  {
    image: "assets/images/Link1.png",
    title: "Day Trading Idea and Strategy",
    categoryName: "Business",
    categoryDistance: "(5 km)",
    date: "Mon, Mar 18 · 7:00 PM PDT",
    participantsItem: "1 going",
  },
  {
    image: "assets/images/Link2.png",
    title: "Let's Talk Networking: JPMorgan Chase in Palo Alto",
    categoryName: "Business",
    categoryDistance: "(25 km)",
    date: "Tue, Mar 19 · 5:00 PM PDT",
    participantsItem: "41 going",
  },
  {
    image: "assets/images/Link3.png",
    title:
      "Tech Talks & Quiz: Next-Gen Database Solutions for Emerging Use Cases",
    categoryName: "Technology",
    categoryDistance: "",
    date: "Wed, Mar 13 · 6:00 PM PDT",
    participantsItem: "40 going",
  },
  {
    image: "assets/images/Link4.png",
    title: "INFORMS San Francisco Chapter In-Person Event",
    categoryName: "Health and Wellbeing",
    categoryDistance: "(50 km)",
    date: "Thu, Mar 28 · 5:00 PM PDT",
    participantsItem: "41 going",
  },
  {
    image: "assets/images/Link5.png",
    title: "AI Wednesdays - Meet and Greet!",
    categoryName: "Technology",
    categoryDistance: "(5 km)",
    date: "Wed, Mar 13 · 6:30 PM PDT",
    participantsItem: "29 going",
  },
  {
    image: "assets/images/Link6.png",
    title: "ROS By-The-Bay March 2026",
    categoryName: "Social Activities",
    categoryDistance: "",
    date: "Thu, Mar 21 · 6:00 PM PDT",
    participantsItem: "51 going",
  },
  {
    image: "assets/images/Link7.png",
    title: "Free Christian Singles' Dinner",
    categoryName: "Hobbies and Passions",
    categoryDistance: "(10 km)",
    date: "Fri, Mar 29 · 6:00 PM PDT",
    participantsItem: "11 going",
  },
  {
    image: "assets/images/Link8.png",
    title: "In-person: Deep Dive into RAG Architectures (Food served)",
    categoryName: "Hobbies and Passions",
    categoryDistance: "(50 km)",
    date: "Thu, Mar 14 · 5:00 PM PDT",
    participantsItem: "16 going",
  },
  {
    image: "assets/images/Link9.png",
    title: "Amazing On-Demand 15 Min Interviews with Top Coaches and Speakers",
    categoryName: "Business",
    categoryDistance: "(25 km)",
    date: "Thu, Mar 14 · 6:00 PM PDT",
    participantsItem: "13 going",
  },
  {
    image: "assets/images/Link10.png",
    title: "Vision Pro Developers Online Meetup",
    categoryName: "Technology",
    categoryDistance: "",
    date: "Wed, Mar 13 · 7:00 PM PDT",
    participantsItem: "51 going",
  },
  {
    image: "assets/images/Link11.png",
    title: "Significant Musical Moments",
    categoryName: "Hobbies and Passions",
    categoryDistance: "(10 km)",
    date: "Wed, Mar 13 · 6:00 PM PDT",
    participantsItem: "16 going",
  },
  {
    image: "assets/images/Link12.png",
    title: "FREE Webinar : Introduction to Power BI",
    categoryName: "Technology",
    categoryDistance: "",
    date: "Thu, Mar 14 · 5:30 PM PDT",
    participantsItem: "33 going",
  },
];
